"""empty message

Revision ID: 3d6c0ce5fd35
Revises: cc6ec5041adb
Create Date: 2019-12-03 21:48:30.688174

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3d6c0ce5fd35'
down_revision = 'cc6ec5041adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('recipe', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recipe_create_date'), 'recipe', ['create_date'], unique=False)
    op.create_index(op.f('ix_recipe_last_modified'), 'recipe', ['last_modified'], unique=False)
    op.add_column('waiting_recipe', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('waiting_recipe', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_waiting_recipe_create_date'), 'waiting_recipe', ['create_date'], unique=False)
    op.create_index(op.f('ix_waiting_recipe_last_modified'), 'waiting_recipe', ['last_modified'], unique=False)

    # Create an ad-hoc table to use for the insert statement.
    recipe = sa.table('recipe',
                      sa.Column('create_date', sa.DateTime),
                      sa.Column('last_modified', sa.DateTime)
                      )
    waiting = sa.table('waiting_recipe',
                       sa.Column('create_date', sa.DateTime),
                       sa.Column('last_modified', sa.DateTime)
                       )
    # insert data
    op.execute(recipe.update().where(recipe.c.create_date is None).values(create_date=datetime.utcnow))
    op.execute(recipe.update().where(recipe.c.last_modified is None).values(last_modified=datetime.utcnow))

    op.execute(waiting.update().where(waiting.c.create_date is None).values(create_date=datetime.utcnow))
    op.execute(waiting.update().where(waiting.c.last_modified is None).values(last_modified=datetime.utcnow))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_recipe_last_modified'), table_name='waiting_recipe')
    op.drop_index(op.f('ix_waiting_recipe_create_date'), table_name='waiting_recipe')
    op.drop_column('waiting_recipe', 'last_modified')
    op.drop_column('waiting_recipe', 'create_date')
    op.drop_index(op.f('ix_recipe_last_modified'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_create_date'), table_name='recipe')
    op.drop_column('recipe', 'last_modified')
    op.drop_column('recipe', 'create_date')
    # ### end Alembic commands ###
