"""empty message

Revision ID: 5fd4be21909c
Revises: 8c0ed103e8c9
Create Date: 2019-12-10 22:40:55.250908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd4be21909c'
down_revision = '8c0ed103e8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiting_recipe', sa.Column('refused', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiting_recipe', 'refused')
    # ### end Alembic commands ###
