"""empty message

Revision ID: 8c0ed103e8c9
Revises: cc6ec5041adb
Create Date: 2019-12-05 21:59:47.254885

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8c0ed103e8c9'
down_revision = 'cc6ec5041adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('recipe', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recipe_create_date'), 'recipe', ['create_date'], unique=False)
    op.create_index(op.f('ix_recipe_last_modified'), 'recipe', ['last_modified'], unique=False)
    op.add_column('waiting_recipe', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('waiting_recipe', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_waiting_recipe_create_date'), 'waiting_recipe', ['create_date'], unique=False)
    op.create_index(op.f('ix_waiting_recipe_last_modified'), 'waiting_recipe', ['last_modified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waiting_recipe_last_modified'), table_name='waiting_recipe')
    op.drop_index(op.f('ix_waiting_recipe_create_date'), table_name='waiting_recipe')
    op.drop_column('waiting_recipe', 'last_modified')
    op.drop_column('waiting_recipe', 'create_date')
    op.drop_index(op.f('ix_recipe_last_modified'), table_name='recipe')
    op.drop_index(op.f('ix_recipe_create_date'), table_name='recipe')
    op.drop_column('recipe', 'last_modified')
    op.drop_column('recipe', 'create_date')
    # ### end Alembic commands ###
