export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const LOAD_DETAILS_START = "LOAD_DETAILS_START";
export const LOAD_DETAILS_FAIL = "LOAD_DETAILS_FAIL";
export const LOAD_DETAILS = "LOAD_DETAILS";
export const LOAD_DETAILS_SUCCESS = "LOAD_DETAILS_SUCCESS";

export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
export const AUTH_USER = "AUTH_USER";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";
export const AUTH_INITIATE_REFRESH = "AUTH_INITIATE_REFRESH";
