export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_RECIPES_START = "FETCH_RECIPES_START";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL";
export const CHANGE_PAGE = "CHANGE_PAGE";
